alex-pinkus/tree-sitter-swift

corpus/classes.txt
corpus/expressions.txt
corpus/functions.txt
corpus/statements.txt
grammar.js
script-data/known_failures.txt

Declarations for functions, classes, and variables are legal at various
different scopes (global, type-level, and local), but have different
sets of legal modifiers in each. While you might think that would be
fine and would simply improve our permissiveness, it actually ends up
_restricting_ some valid code - in particular, code that uses those
would-be modifiers as identifiers. For instance, one file in Carthage
uses the innocent-looking variable name `prefix`, but we fail to parse
that because in other scopes, that would instead be a modifier.
To fix this, we split out declarations by scope: global, type-level, and
local. For now, we treat global and type-level as mostly the same except
that subscripts are legal in the latter and not the former. However, for
local declarations, we …

Add restrictions on modifiers in local scope

---

grammar.js
script-data/known_failures.txt

We still need to move the custom operator logic to the scanner, but
that's a lot of complexity, and it's still unclear how to do that
without a lot of breakage. Instead of doing that now, we just special
case handling of `<` (which is what was tripping up a lot of Carthage
files).
With this change, #5 will no longer be a top-repos-error, even though it
will still be a valid bug.

Minorly improve custom operator handling

---

corpus/classes.txt
corpus/expressions.txt
corpus/literals.txt
grammar.js

I want to add a big new repository into top-repos, but we're failing
a bit more than I'd like (and there's some optimization work to do).
Still, there's no reason not to land the fixes while improvements
continue.
- Allow implicitly unwrapped types in a few more places
- Fix unicode escape handling in strings
- Add a few more special literals
- Add ! as a possible character in an init
- Add the dynamic modifier for class members
- Allow subscript declarations in protocols

Implement fixes from some repos that aren't being tracked yet

---

corpus/classes.txt
grammar.js

The grammar suggests that protocol composition types are only allowed "when
specifying a type in type annotations, in generic parameter clauses, and in
generic where clauses." The corpus of valid code seems to imply
otherwise. Instead, we just allow these everywhere, and resolve
ambiguity the same way the compiler appears to by giving them right
precedence.
Fixes #46
Also bundled the one-liner fix for #50

Allow protocol composition types everywhere

---

corpus/expressions.txt
grammar.js

The right hand side of an `is` should be a type, not an expression.
Fixes #49

Make check expressions behave properly

---

corpus/functions.txt
src/scanner.c

It's possible to define a custom operator like `???`, even though that
starts with the built-in nil coalescing operator. Our custom scanner
doesn't allow this today. What we need to do is check whether the
character _after_ the end of a built-in operator is a valid continuing
character for a custom operator, and only emit the built-in operator if
it isn't.
For simplicity, this doesn't handle all of the unicode characters that
are allowed in a custom operator, because they mostly don't get used.
When we move the custom operator handling _fully_ to the custom scanner,
that's probably the right time to revisit this.
Fixes #45

Don't emit a built-in operator if it could be a prefix for a custom one

---

corpus/classes.txt
grammar.js

Swift allows `return a = b` and stuff like that. We can do that too, we
just have to move some definitions around and change precedence.

Treat assignment as an expression

---

.github/workflows/top-repos.yml
script-data/known_failures.txt
script-data/top-repositories.txt
scripts/top-repos.sh

Adding functionality to specify "part X of Y" of a repository. This
allows two things to happen:
1. In CI, that repository will get split across multiple Github Actions
hosts, each one having less work to do
2. Running locally, the script will spin off each validation check as
its own process and they will all return more quickly.
This is necessary to add `firefox-ios` as a top repository since it has
657 swift files, which would otherwise take 5 minutes on CI, and I'm not
ready to wait that long.
Fixes #49

Parallelize locally and allow split repositories

---

script-data/known_failures.txt

These might have been fixed recently or have maybe been working for a
while. In any case, it's best to remove them from known-failures so that
they cannot regress.

Remove some no-longer-failing known failures

---

corpus/expressions.txt
grammar.js
script-data/known_failures.txt

It is definitely legal (and has always been valid) to do something like:
```
SomeType.someMember
```
This has a type on the left-hand side and a member access on the
right-hand side. This grammar so far has been OK with that simple case,
because all it knows is that there's an identifier on the left. However,
this breaks down when we do the equally legal:
```
SomeGenericType<TypeParam>.someMember
```
because now this is _not_ an identifier on the left. To fix this, we
allow a few specific forms of a `_type` in a navigation expression. The
allowed types are exactly the ones that do not cause parsing
ambiguities, because that handles the cases that seem to exist in real
life.

Allow generic type params in member expressions

---

corpus/comments.txt
corpus/statements.txt
grammar.js
script-data/known_failures.txt
src/scanner.c

Fixes #47
Adds `catch` to the semi suppressor, and also suppresses semis at the
start of a comment. This also required a bit of rework that's been
overdue for a while, to not suppress _explicit_ semicolons - those don't
get used much, but there was one test case where one of those was
followed by a comment.

Fixing newlines and comments for if/else and do/catch

---

.github/workflows/top-repos.yml
grammar.js
script-data/known_failures.txt
script-data/top-repositories.txt

Most of the parse failures in RxSwift can be fixed with two trivial
changes:
* Allowing `+` to be an operator reference (should have done already,
but was afraid of adding it as a conflict)
* Loosening validation on `...` identifiers
With these, we get a 99.8% parse rate on that repo, so it would be
a shame _not_ to add it to `top-repos`. The two remaining failures are
more insidious - one for emoji identifiers, the other involving binding
in nested tuple patterns. Both will be handled as their own bugs.

Add fixes for `RxSwift`, and then add that as a top repository

---

corpus/classes.txt
corpus/expressions.txt
corpus/functions.txt
corpus/statements.txt
grammar.js
src/scanner.c

- Create conflict for capture list items
- Guard statements are not expressions
- Support more compiler control statements
- Support optionals in patterns that have already been bound
- Add some more characters to the semi suppressor

Miscellaneous fixes for minor rare compile failures

---

corpus/classes.txt
grammar.js

The ArgumentParser library makes heavy use of custom attributes (are
they even called attributes here?). The grammar needs to respect those
rather than treating them as some sort of malformed `@available(...)`
attribute.
This change gives us a bit more structure to what we expect to see in an
attribute, whether built-in or custom.

Allow expressions in annotation attributes

---

corpus/statements.txt
grammar.js

- Allow type annotations on if/guard case conditions
- Allow `for var` without `case`

Fix pattern matching edge cases

---

corpus/expressions.txt
grammar.js
script-data/known_failures.txt
scripts/top-repos.sh
src/scanner.c

Not all the operators in `scanner.c` are the same. In some cases, the
operators should be ignored if the character after them potentially lets
them be a custom operator themselves. In other cases, the operator
should be ignored if it's followed by alphanumeric characters (since
that would make it an identifier).
We solve this by adding a new list for the "illegal terminators" and
checking against those. This has the bonus of letting us add two new
semi suppressors:
1. `as`, the bare keyword, now that we aren't fooled by having it at the
start of a word
2. `+` and `-`, but only when followed by whitespace - when there's no
whitespace between the operator and the subsequent token, but there _is_
whitespace before it, Swift treats it as a prefix operator. We just have
to check the trailing …

Disallow different characters after certain operators

---

grammar.js

The keyword `indirect` is legal on an enum class declaration or on an
individual case, and tells the compiler to use the heap to avoid an
infinitely sized structure. Add the keyword directly into those places
where it is legal.

Add support for recursive enums

---

corpus/statements.txt
grammar.js

The grammar erroneously had it that a switch _case_ would get a single
`where` clause, disallowing something like:
```
case .foo(x) where x.count() == 0, .bar(x):
```
Allowing `where`-clauses per pattern is strictly more flexible.

Where clauses go on switch patterns, not cases

---

package.json
scripts/test-with-memcheck.sh

Corpus tests run very quickly and we don't care about their output (just
about the return code). This makes them a great candidate for running
under `valgrind`.

Run corpus tests using memcheck

---

corpus/expressions.txt
corpus/statements.txt
grammar.ts

There are a few bugs with things that don't quite have the right
precedence, like ranges and `try`. This commit reworks all of those to
return what appear to be the correct results.
This also reorganizes precedences to be a bit more friendly and, rather
than dealing in integer values, just dealing in relative positions.
Seeing at a glance that "try and ternary are both at the same position"
is more immediately useful than seeing that they are at position X.
Fixes #1
Fixes #3

Overhaul precedences

---

grammar.ts

In most places in the grammar, we rely on our conflicts resolving
themselves with only one parse interpretation being valid. With `try` and
ternary, that isn't the case: both of `try (foo() ? bar() : baz)` and
`(try foo()) ? bar() : baz` are valid. This matters because `bar()`
could also be a `throws` function, and our `try` is supposed to cover
it.
The rules for dynamic precedence are described here:
https://github.com/tree-sitter/tree-sitter/issues/678
Based on those, it seems like we were getting the correct parse result
in our test cases solely because of some rule definition order, which
"isn't really meant to be relied on." This exposes itself in some
unrelated changes for a custom string interpolation (not included in
this PR) where the rule order changes and flips our …

Fix inconsistent conflict resolution for `try` and ternary

---

corpus/literals.txt
grammar.ts

Swift has a magical syntax for string interpolation that involves
special `appendInterpolation` functions and causes the interpolation to
look like a value argument.
This adds support for that.

Add support for custom interpolation syntax

---

corpus/expressions.txt
corpus/functions.txt
grammar.ts
src/scanner.c

Allows async in function declarations and type signatures. `async` must
always come before `throws`. This keyword also has to go in the semi
suppressor for the same reason `throws` and `rethrows` are there.
Also allows `await` before any expression. Gives it the same special
behavior that `try` gets, where it has an affinity for function calls
and ternary operators, but can be placed before any expression.
Special cases the `for try await` syntax that Swift added for async
sequences. That doesn't appear to have made it into the grammar yet.
Usage makes it seem like it must be either `for await` or
`for try await`, not permiting just `for try` alone, but without an
official reference it seems best to simply allow `for try`.

Add `async` / `await`

---

corpus/classes.txt
corpus/functions.txt
grammar.ts

- Support attributes within lambda literals
- Support annotated inheritance specifiers

Support attributes in a few places where they should be legal

---

corpus/functions.txt
grammar.ts

Adds all the prefix unary operators that aren't either already present,
or the dot operator.

Allow a few more built-in operators to be overloaded

---

corpus/classes.txt
grammar.ts

Allows the final `_semi` (whether it's a real one or implied by
whitespace) to be omitted if a caller desires.

Allow a class to be defined on one line

---

corpus/classes.txt
grammar.ts
script-data/known_failures.txt

The semi-suppressor is a little too aggressive: if it sees something
like:
```
class Foo {
let property1: String
/* visible for testing */ var property2: String
}
```
It will suppress the newlines before `property2` and cause compilation
to fail. If the comment were on its own line, it would be fine, because
there's still another semi in the way.
The best way to fix this seems to be to allow multiline comments
themselves to count as separators.

Allow declarations that start with a multiline comment

---

.github/workflows/top-repos.yml
README.md
scripts/calculate-parse-rate.sh
scripts/common.sh
scripts/top-repos.sh

This uses the Bring Your Own Badge github action, running a script to
count the number of swift files and generate a percent based on the
count of files in `known_failures`.
This script only runs once the top-repos job has completed,
successfully, on a code push, so all it needs to do is compare
`known_failures` against the number of Swift files in the repos.

Add a badge for parse rate

---

corpus/expressions.txt
grammar.ts
src/scanner.c

So far, we've tolerated the parser treating `!.` as one operator when it
should really be two. This changes that behavior so that we better match
the actual semantics of `!.`, which is a bang-operator followed by
navigation.
We do this by adding `!` to the custom scanner, but this also requires
us to generalize the custom scanner's operators and indicate that they
are not all cross-semi operators. That's because `!` at the start of a
line is valid (although it will usually result in a warning) - it gives
us a standalone expression that negates what comes after the `!`.

Use the custom scanner to split ! from .

---

corpus/classes.txt
corpus/expressions.txt
corpus/functions.txt
corpus/literals.txt
corpus/statements.txt
corpus/types.txt
grammar.ts
queries/highlights.scm
queries/locals.scm
script-data/known_failures.txt

Puts some basic syntax highlighting in place for keywords and
identifiers. This requires some nodes to lose their anonymity, in
particular any keyword that we wish to match from the custom scanner.

Add queries for syntax highlighting

---

.github/workflows/publish.yml
.github/workflows/top-repos.yml
README.md

Assumes that the crates.io and npm versions will stay the same (they should) and uses the npm publish output as an input for a badge publishing job.
As a side effect, only runs the crates.io publish logic after updating the package in npm, because this will allow for batching of minor changes together under a single version update. The crates.io publish action will otherwise just fail if it doesn't like what it sees.

Publish status badges for crates.io and npm packages

---

.github/workflows/top-repos.yml
package-lock.json
package.json
scripts/test-with-memcheck.sh

Applies suggested fixes from #87:
* Pointing to `./build/grammar.js` in install command
* Putting `typescript` in `dependencies` rather than `devDependencies`
* Running `binding` during install (this change does it during
`postinstall` rather than `preinstall` so that the `parser.c` is
present when clean)

Fix clean `npm install` behavior

---

Cargo.toml
README.md
corpus/classes.txt
corpus/expressions.txt
corpus/functions.txt
corpus/literals.txt
corpus/statements.txt
corpus/types.txt
grammar.ts
package-lock.json
package.json
queries/highlights.scm
test-npm-package/package-lock.json

Some minor fixups from trying to use the parser, mainly adding fields
for the elements of most common nodes. Also some minor rearranging of
the AST: things like putting external parameter names within the
parameter nodes, rather than right before, which are non-backwards
compatible so it's best to do them early.
The corpus really didn't change much, but `tree-sitter test -u`
reformatted it. This is a one-time cost and now that we're using the
auto-updated formatting, the diffs will be much cleaner from now on.
Includes a version bump to `0.0.2`, which is good because it's an
opportunity to republish the package with the publishing fixes from #93.

Add field names for common queries

---

Cargo.toml
README.md
bindings/rust/lib.rs
corpus/classes.txt
corpus/functions.txt
grammar.ts
package.json
test-npm-package/index.js
test-npm-package/package-lock.json

In advance of reaching 0.1, adding a few more field names should make
stability guarantees easier to satisfy.
Also promotes `protocol_composition_type` to named which breaks semver,
so bumping to 0.0.3.

Add field names to a few more nodes

---

Cargo.toml
README.md
bindings/rust/lib.rs
package-lock.json
package.json
test-npm-package/index.js
test-npm-package/package-lock.json
test-npm-package/package.json

It turns out (#92) that some libraries rely on the name of the `tree-sitter` packages always being `tree-sitter-.*`. Rather than trying to take some secondary title of `experimental-swift` or similar, we can simply drop the `experimental` and bring balance to the force.
Fixes #92

Grand renaming and 0.1-ing

---

.github/workflows/check.yml
.gitignore
Cargo.toml
README.md
grammar.js
package-lock.json
package.json
scripts/test-with-memcheck.sh
test-npm-package/package-lock.json

Installing the grammar from `build/grammar.js` works for normal install
commands but leaves the user unable to run `tree-sitter` commands from
the current directory. That's because specifying a `grammar.js` path
causes the CLI to skip writing a `grammar.json` (which is debatably a
bug in the CLI). Other scripts currently work around this by running
`tree-sitter generate` themselves, relying on a symlink into the build
directory. That doesn't work on Windows, though.
This changes the install script so that it copies the `grammar.js` into
the current directory and then uses the copied one. With this change, we
get our `grammar.json` simply by running `npm install`!

Improve install behavior on Windows

---

Cargo.toml
README.md
grammar.ts
package-lock.json
package.json
test-npm-package/package-lock.json

Currently `?` is not visible in the syntax tree because it's anonymous.
Fixes #100

Add an alias for `?` in type position

---

queries/highlights.scm

The folks over at `nvim-treesitter` have kindly made some improvements
to the highlight queries to address a few gaps. By adding them here, we
can ensure that everyone benefits!

Incorporate query improvements from nvim-treesitter

---

.github/workflows/update-repos.yml
script-data/known_failures.txt
script-data/top-repositories.txt
scripts/update-top-repos.sh

Adds a script to automatically fetch the latest tag available for each
repository, so that we get alerted to any new code that can't be parsed.
This is intended to be run on a regular basis.
Also updates the top repositories to match the values that this script
finds.

Update top repository tag versions in CI

---

.github/workflows/check.yml
.github/workflows/parser-src.yml
.github/workflows/top-repos.yml
README.md
scripts/update-top-repos.sh

* Separate publish action (of grammar.json, etc) from check.yml
* Skip running `test-ci` when testing GitHub repos
* Don't publish repo updates as draft

Tweak CI actions

---

corpus/classes.txt
grammar.js

Fixes #8
Just uses `conflicts` to allow the keyword to appear anywhere instead of
special casing it.

Allow the modifier `class` to appear in any order

---

.github/workflows/check.yml
package-lock.json
package.json
scripts/wait-for-tree-sitter.js

The `tree-sitter` command is not guaranteed to exist at the time that
its `install.js` terminates. It may still be downloading the appropriate
binary, or may not have marked it as executable.
To work around this, we update our install script to wait for the file
to be marked as executable before we run `tree-sitter generate`. This is
a workaround for the real issue and can be removed once the real issue
is fixed.
Fixes #119

Wait for tree-sitter to exist before generating

---

queries/highlights.scm

I'm not certain why another parser might use `#lua-match?`, but `#match?` is more standard across the tree-sitter ecosystem, and is fairly well-supported by a number of highlighting bindings, including tree-sitter's own rust implementation.

Use generic match predicate

---

grammar.js

See https://github.com/returntocorp/ocaml-tree-sitter-semgrep/issues/286
When generating a simplified grammar, the `ocaml-tree-sitter` code generator forces all hidden nodes to be visible. It appears that hidden nodes automatically get marked as `inline`, and that without that auto-inlining, the `_locally_permitted_modifiers` rule causes a conflict.
Rather than making the semgrep folks work around their conflict, we just check the `inline` declaration into the grammar itself so that it sticks around in the simplified grammar.

Manually inline `_locally_permitted_modifiers`

---

corpus/classes.txt
grammar.js

This removes 2 of 17 anonymous CST nodes that ocaml-tree-sitter-semgrep generates from this grammar. The test changes are just the addition of the new `computed_property` node in the tree in some places.

Remove duplicate grammar fragment for computed properties

---

corpus/statements.txt
grammar.js

This removes another anonymous CST node when this grammar goes through ocaml-tree-sitter-semgrep.

Remove duplicate grammar fragment for binding pattern kind

---

grammar.js
queries/highlights.scm

This makes obsolete the overly-broad `@variable` rule on
`simple_identifier`, while still marking bound variable names as
variables.

Add a field name for bound identifiers

---

queries/highlights.scm

I found that the simple_identifier variable is too broad, it overlaps with many other patterns. I believe it's ok to remove it from the top level.

highlight query update

---

grammar.js

This is a little different than the other changes I've made recently. It doesn't deduplicate anything in the grammar, but it still removes an anonymous node in the CST generated by ocaml-tree-sitter-semgrep. This is because ocaml-tree-sitter-semgrep chooses to inline the availability_condition rule into the `if_condition_sequence_item` rule. Because of this, it previously generated an anonymous type in the CST corresponding with the fragment that is now called `_availability_argument`.

Refactor availability_argument rule

---

grammar.js

Even though this does not appear at first to remove any duplication, this still removes an anonymous CST node that was previously generated by ocaml-tree-sitter-semgrep. This is because the `sep1` function duplicates its first argument in the resulting grammar.

Factor out enum_entry_suffix rule

---

.gitignore
Makefile
bindings/c/tree-sitter.pc.in

In https://github.com/alex-pinkus/tree-sitter-swift/pull/111 @krzyzanowskim added a Makefile and C bindings. These differed from the original "standard" version, but were better in many ways. I used this version as a template to fix up the existing Makefiles in other parsers, and in the process made just a few changes. I'm now moving those back here.
- Uses more built-in make functions
- Correctly assigns the parser URL in the pkgconfig file
- Treats the .pc file as a build artifact, just the .h
- Changes the header name from `tree_sitter/tree-sitter-swift.h` to `tree_sitter/swift.h`
The last one does have the potential to cause issues. But, it seems worth standardizing the header name to match other how other parsers do it.
I will coordinate a fix for …

Standardized makefile and c bindings

---

.github/workflows/generate-static-grammar.yml
scripts/write-generated-grammar.sh

Certain consumers of tree-sitter do not wish to take a dependency on the CLI in order to generate their grammars. Long-term, those consumers will be able to use packaging systems like tspm or obtain grammars from github actions. In the short term, though, not packaging the grammar means that there is no way for them to consume it.
This creates a GitHub action that will push the static grammar to an isolated branch of this repository, allowing those systems to use GitHub as a kind of hosting system for grammar artifacts. We push the grammar on creation of a new ref to keep the number of deltas relatively low.
Fixes #149

Commit generated grammar on an isolated branch

---

corpus/expressions.txt
corpus/statements.txt
grammar.js

Should I apply this similar pattern for other binary operators too? Or is there a nicer way to do it :O ?

Fix incorrect parsing of binary expressions (fixes #153)

---

corpus/comments.txt
src/scanner.c

Fixes #159
This was the same problem as #146, where there was a `while` loop in the custom scanner that terminated on newlines but not on EOF. To fix, we just terminate on EOF for this loop as well.

Fix hang when the last line is a comment

---

grammar.js

See #166
Unfortunately, it doesn't look straightforward to include this example in the tests.
```
$ echo -n "print(3)" > nonewline.swift
$ npx tree-sitter parse nonewline.swift # No parse error
```

Parse files that end without a newline or semicolon

---

corpus/annotations.txt
corpus/classes.txt
corpus/emojis.txt
corpus/expressions.txt
corpus/functions.txt
corpus/literals.txt
corpus/statements.txt
corpus/types.txt
grammar.js
queries/highlights.scm
script-data/known_failures.txt

This change loosens pattern validity requirements for the sake of greatly simplifying the grammar.
This isn't going to be backwards compatible, so let's take the opportunity to figure out what the names rules _should_ be for patterns -- the current `(value_binding_pattern (non_binding_pattern ... ))` situation is confusing.
It should be possible to do away with `generate_pattern_matching_rule` entirely. After doing that, finding the right combo of named rules (or maybe aliases) should make this mergeable.
See #9
Fixes #61

WIP: Simplify pattern rules

---

src/scanner.c

For some reason, we were continuing to look for more whitespace tokens after consuming an explicit semicolon. This is unnecessary since the scanner can just come back for the remaining whitespace, if any exists. It also leads to incorrect attribution of the location of the semicolon, so it's better to just break at the semicolon.
Fixes #177 -- with this change, the test file in that issue gets parsed as:
```
(source_file [0, 0] - [2, 0]
(simple_identifier [0, 0] - [0, 3])
(_semi [0, 3] - [0, 4])
(simple_identifier [1, 0] - [1, 3])
(_semi [1, 3] - [1, 4]))
```

Fix semicolon line attribution

---

grammar.js

Partially-addresses #132
Previously, ocaml-tree-sitter generated an anonymous CST node for this fragment, since the `sep1` helper function makes its first argument appear twice in the generated grammar. By naming it, ocaml-tree-sitter no longer has to come up with a name for this fragment when it extracts common grammar fragments.
A shift/reduce conflict between the first and third choice options exists. I believe that this was already covered by the `attribute` entry in the conflicts list, so I added `_attribute_argument` to that list as well. I do not believe that this is a true ambiguity in the grammar, since it could be resolved with arbitrary lookahead, so allowing tree sitter to explore both options should lead to a correct parse in all cases. I would appreciate a sanity check on my …

Split attribute argument into its own rule

---

package-lock.json

I have npm v8.3.1 and every time I run `npm install` it makes this
change.
Lockfile version 2 is backwards-compatible with version 1, and was
introduced in npm v7:
https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json#lockfileversion
npm v7 was released in 2020:
https://blog.npmjs.org/post/631877012766785536/release-v700.html

Update lockfile to v2

---

grammar.js

The `sep1` helper makes its first argument appear twice in the generated grammar, so ocaml-tree-sitter pulls out that fragment. This gives that fragment a name so that it doesn't have to come up with one on its own.

Split _modifierless_property_declaration rule

---

grammar.js

Fixes #132
(when combined with #180 and #182)
This fragment was used twice, so ocaml-tree-sitter generated an anonymous CST node for it.
I developed #180, #182, and this in one branch before splitting them off for easy review, so they should not conflict with each other.

Split expr hack suffix into its own rule

---

grammar.js

This is a weird one.
I found that under certain circumstances, the pattern `foo(1, 2)` was not matching the source file `foo(1, 2)` in Semgrep. When I looked at the CST generated by tree sitter, I found that if `foo(1, 2)` is followed by a newline, it is parsed as a call, but if it is not, it's parsed as a constructor. Often, patterns are provided over the command line and do not include a newline, whereas source files usually do. I tried to reproduce the difference in parsing using tree sitter directly, and could not. This puzzled me. I considered the possibility that the extensions we've made to the grammar to parse Semgrep constructs might have affected this, but that seemed far-fetched to me.
I recalled that calls and constructor calls are truly ambiguous with each other, so I decided …

Increase dynamic precedence of call

---

corpus/statements.txt
grammar.js

We do not add the hack into additive / multiplicative expressions
because, for some unexplained reason, that causes the expressions to be
right associative. I'll come back that later to investigate.

Add call expr binary hack in a few more places

---

queries/locals.scm

`@scope` is an invalid name according to documentation: https://tree-sitter.github.io/tree-sitter/syntax-highlighting#local-variables, therefore use `@local.scope`. This fixes tree-sitter cli that error on unknown `@scope`

Fix locals scope

---

corpus/functions.txt
corpus/types.txt
grammar.js

- Add support for existential types (`any Something`) -- these were defined in [SE-0335](https://github.com/apple/swift-evolution/blob/main/proposals/0335-existential-any.md) but don't appear to have made it into the official grammar yet.
- Fix placement of lambdas in annotations -- we were erroneously assigning those to parameters or capture clauses but in fact they only belong to the closure itself.

Fix Nuke parse failures

---

.gitignore
Package.swift
bindings/c/tree-sitter.h.in
bindings/c/tree-sitter.pc.in
bindings/node/binding.cc
bindings/node/index.js
bindings/rust/build.rs
bindings/rust/lib.rs
bindings/swift/TreeSitterSwift/swift.h

This PR adds `Package.swift` and related files into the repository on the `with-generated-files` branch. This will get automatically updated on each new release, allowing downstream systems to consume the repository without needing to build from source.
Originally, the goal was to create a SwiftPM build tool that could compile all necessary files from source. This turned out to be infeasible because:
1. It would still require the `tree-sitter` _binaries_ to be checked into this repository. Why? Because `tree-sitter` normally distributes itself as binary (e.g. in the NPM [`install.js`](https://github.com/tree-sitter/tree-sitter/blob/a882d0b036b0da23cde5caa1325089b4ca4750ba/cli/npm/install.js) which just wraps a download script) but SwiftPM builds are sandboxed. This is unfortunate, but not …

Add SwiftPM manifest file

---

corpus/expressions.txt
corpus/functions.txt
grammar.js

Fixes #2 (Finally!)
This requires us to introduce a conflict since call arguments can be
neither left associative nor right associative.

Treat foo() { } as one call, not two

---

corpus/classes.txt
grammar.js
script-data/known_failures.txt

Because this is technically not allowed, allowing it here means that we end up _disallowing_ `lazy` as an identifier in local scope (which is wrong -- it's a default function on collections!)
This fixes a top-repo error!

Disallow `lazy` as a local variable modifier

---

grammar.js

* Allow single-arg functions to omit parentheses
* Allow operator declarations to have bodies
* Allow where-clauses within a generic parameter list
* Allow multiple sets of function parameters
* Allow where-clauses in `if let`

Add support for very old Swift constructs

---

.github/workflows/top-repos.yml
corpus/expressions.txt
corpus/functions.txt
grammar.js
script-data/known_failures.txt
script-data/top-repositories.txt
src/scanner.c

Custom operator rules are better expressed as conditions to track in `eat_operator` vs a series of impenetrable regexes.
Also requires a fix for an undiscovered bug where `x[...]!` was not considered to be a legal target for an expression. Since the old logic allowed `+=` to be a "custom operator", we were covering up for that failure by interpreting `x[...]! += y` as a custom infix expression.
This fixes the last parse failure in the current list of top repos, so we also bring in some new top repos. The new list comes from the ones the Semgrep folks have added for their own parse rate tracking. For some reason, Semgrep uses very old repos, so we have to support older language constructs.
Fixes #5

Move custom operator handling to `scanner.c`

---

queries/highlights.scm

After the pattern refactor, the highlight query for `for_statement` was never updated, and now refers to a pattern that cannot happen (a `simple_identifier` directly under a `for_statement`). In addition to being wrong, this gets rejected by older versions of `tree-sitter`.
Fixes #219

Fix impossible pattern in highlight queries

---

.github/workflows/check.yml
.github/workflows/test-older-tree-sitter.yml
package-json-old-tree-sitter.json

In #221, we fixed a bug where older versions of tree-sitter failed to parse highlight queries because they were impossible.
Since we know that some editors use an older version of tree-sitter, it would be prudent to test against it in CI.

Check queries against older tree-sitter versions

---

corpus/expressions.txt
src/scanner.c

- Fix handling of custom operators when a slash was already consumed:
- This logic was not working properly when the whitespace handler attempted to consume a slash already. To handle that, we give the `eat_operator` function some more information about the surrounding context of the possible prior character that has been eaten.
- Don't allow a three-dot operator after a newline:
- The Swift compiler actually doesn't allow this with _any_ whitespace around it, but that's more annoying to accomplish. Instead, we simply hard-code the three dot operator as "invalid" if we've already crossed over an implicit semicolon boundary. Once we emit the `_semi`, the three-dot operator will no longer be legal anymore, so it will be missed on the next pass as well.
- We don't add a test for this because …

Fix operator handling with custom ops that start with `/`, and with `...`

---

corpus/expressions.txt
grammar.js
src/scanner.c

We now have better invalidation of operators in the custom scanner than we did when we added the various `.`-prefixed operators. This means we can bail out quickly and avoid marking a token incorrectly.
This simplifies downstream handling of `...`, which, in addition to being a Swift operator, is also used by Semgrep.
In order to make this happen, we do also have to be a bit more careful with `mark_end`. If we're possibly going to emit a `_semi`, we have to make sure not to `mark_end`, because we don't want that to be "part of" the semi. This theoretically means that if we were chasing a longer operator, but failed to find it, and had a shorter operator that was `cross_semi`, it would get parsed incorrectly -- but this seems unlikely since such a longer operator would be likely to match …

Don't use the external scanner for `...`

---

Makefile

Currently, a non-clean build after updating `grammar.js` will not pick up any new changes. This happens because as far as the makefile is concerned, `parser.c` is a source file, and it has not been updated.
To fix this, we simply add a rule that can generate `parser.c`. If someone runs `make install` after `npm install`, this rule will do nothing, because the output file will already be newer. However, if someone updates the repo, this will ensure all artifacts get updated.
Fixes #229

Regenerate parser.c in Makefile when grammar changes

---

.gitignore

Super minor, but I noticed it was missing.

Ignore SPM .build directory

---

package.json

Somewhat ironically, we must opt out of the ABI 14 query improvements that were turned on by default in 0.20.7. That's because no version of `node-tree-sitter` has been published that supports ABI 14. Hopefully this is a temporary state that we can fix later!
Fixes #236

Pin tree-sitter-cli to 0.20.6

---

corpus/literals.txt
grammar.js
queries/highlights.scm

This has a few unfortunate differences from the official parser:
1. Doesn't handle the "unbalanced parentheses" rule, because that
would require an external scanner implementation (probably will happen
someday!)
2. Doesn't insert an implicit semicolon between the regex and the
previous line. This is mostly fine but causes problems with the "Regex
builder DSL".
3. Doesn't match opening and closing `#` symbols in multiline regexes,
for the same reason as point 1

Partial regex literal support

---

Package.swift

`SwiftTreeSitter`, which we know practically is the one package wrapping `tree-sitter` that builds in SPM, uses a git submodule that points to 0.20.7. Before it did that, it didn't pin a version in the submodule, and before it had submodules it pointed to a fork of `tree-sitter` directly.
Because of this, we know that it's extremely unlikely that anyone would build `tree-sitter-swift` in SPM and require ABI 13 compatibility. This is different from, say, NPM, where we know the opposite is true. However, because we know this here, we can significantly speed up query parsing by using ABI 14.
On my local machine, this consistently halved the time it took to run a simple test that just loaded queries and did nothing else.
Before:
```
real	0m4.376s
user	0m4.262s
sys	0m0.118s
```
After:
```
real …
```

Use ABI-14 parser when compiling for SPM

---

queries/highlights.scm

`nvim-treesitter` has a few updates that it would make sense to bring in:
* Using `@function.call` rather than just `@function`: should fall back to the more-generic highlight anywhere the specific one isn't supported
* Adding `@spell`: harmless if that isn't recognized
We do retain the one difference around `#match` vs `#lua-match`, since that was a PR made directly as a divergence.

Sync queries with nvim-treesitter

---

grammar.js
package-lock.json
queries/highlights.scm

Requires a redundant alias to get it to show up as a node.
Also updated an out-of-date package lock.

Add await to highlighted keywords

---

grammar.js
script-data/top-repositories.txt

The keyword `lazy` can also be used as an identifier. Previously, we resolved this by saying it wasn't usable in local scope, but that's not actually quite right. We just have to define it in both places and let it conflict like `actor` does.

Allow lazy as a local modifier

---

.github/workflows/publish.yml
Cargo.toml

ABI 14 has been out for a year, so it's time to bump our version constraints.
Fixes  #271

Regenerate using ABI 14 before publishing to crates.io

---

queries/indents.scm

`nvim-treesitter` has now been using Swift indents for some time without
any complaints. Copying those indents verbatim upstream so that other
IDEs can support them too.
Fixes #322

Add indents used in nvim-treesitter

---

grammar.js
test/corpus/expressions.txt

We currently only allow a subset of expressions to be used as the target of assignment. The Swift compiler also only allows a subset, but keeping track of their subset is hard. For example, in #321 
we see that an optional expression can be used for assignment but we don't currently support that.
Let's get out of that game. All expressions can be assignments now! Sure, that doesn't work for the real swift compiler, but that's not our circus, and furthermore, not our monkeys.
Fixes #321

Loosen the restrictions around directly assignable expressions

---

.github/workflows/top-repos.yml
script-data/top-repositories.txt

The repository yichengchen/clashX seems to no longer exist. This will
cause CI to fail until it's removed.

Remove unpublished top repository

---

queries/textobjects.scm

Hi!
I also noticed there wasn't a `textobjects.scm`, and decided to take a crack at it -- this allows for inter-function, (almost) inter-test jumping in [helix](https://github.com/helix-editor/helix), for instance :)
Happy to add more or if y'all want to use as a jumping off point, feel free.
I got setup with the [playground](https://tree-sitter.github.io/tree-sitter/playground), which was relatively simple on macOS:
```sh
brew install tree-sitter
brew install emscripten
tree-sitter build-wasm
tree-sitter playground
```

Add initial textobjects.scm

---

grammar.js
test/corpus/expressions.txt
test/corpus/statements.txt

As pointed out in #351.
[SE-0380](https://github.com/apple/swift-evolution/blob/main/proposals/0380-if-switch-expressions.md)
made it possible to do this, but support was lacking in this repository.
The fix turned out to be easier than anticipated, simply requiring the
statement to be added in some new places. Theoretically, it should also
be renamed, but that would make this a breaking change.
The proposal does not make clear whether labels are permitted on
expression-position `if` and `switch` statements. This assumes they are
not, for simplicity.

Add support for if/switch expressions

---

queries/highlights.scm
test/highlight/ImagePipelineConfiguration.swift
test/highlight/LazyImage.swift

In helix-editor/helix#9586, the Helix editor added highlighting for the `any` keyword.
However, while reviewing that, I noticed that both `some` and `any` should be more specific: these keywords are legal as identifiers, but should not be highlighted as identifiers when they are keywords.
For instance, I can write:
```
let any: any Protocol = AnyImplementation()
```
In this example, only the second `any` should be highlighted.
See discussion on #351.
cc @7ombie

Incorporate changes made in Helix highlight queries

---

grammar.js
test/corpus/classes.txt

The grammar was previously skating by by (erroneously) parsing `willSet`
and `didSet` blocks as computed properties and function calls (with
various combinations). This will usually _parse_ but is never _correct_.

Add explicit support for willSet/didSet blocks

---

grammar.js
script-data/known_failures.txt
test/corpus/expressions.txt

Since this case used a literal "=" in the grammar, rather than an `_equal_sign`, it did not indicate to the scanner that the `=` was an allowed character. This prevented the scanner from suppressing semicolons.

Allow assignment to be split over multiple lines

---

grammar.js
script-data/known_failures.txt
test/corpus/expressions.txt

In #353, adding `_parenthesized_type` caused new parse failures where the parser now resolved away from `tuple_type` too early. Specifically, when parsing an expression like `[(any Foo) ...`, the `tuple_type` interpretation must still be valid at that point in the expression in case we're about to see a `?`.
The truly robust thing to do would be to support `$.tuple_type` as the target of the navigation expression. However, this leads to a large number of additional parse failures, as seen in #360. To avoid all of that, we add support in the opposite direction: allow `tuple_type` to be resolved using `_parenthesized_type`, so that the parser seeing the latter does not cause it to invalidate the former.

Bring back support for optional types in constructors

---

grammar.js
test/corpus/functions.txt

See
[SE-0377](https://github.com/apple/swift-evolution/blob/main/proposals/0377-parameter-ownership-modifiers.md].

Add borrowing and consuming as keywords

---

queries/highlights.scm

Adds special case `#eq?` clauses into the highlight queries for special cases where we have keywords or builtins that aren't in the grammar.
Specifically:
* With `Self`, this is parsed as a boring type identifier, but should be
highlighted as a builtin variable.
* With `defer { }`, this is parsed as a function, but the behavior is
unique enough that it is reasonable to present it as a keyword.
With this and other recent fixes, all of the issues identified in #351 have been fixed.

Highlight Self and defer appropriately

---

queries/highlights.scm

@IronHam notes that it seems jarring to see an init and then deinit method declared in succession where only one gets a special highlighting.

Highlight `deinit` the same as `init`.

---

queries/indents.scm

Copied from https://github.com/nvim-treesitter/nvim-treesitter/pull/6242
Indent tests were not copied because I could not find a way to invoke them from `tree-sitter test`. We'll just have to be more careful in the future.

Add willSet/didSet to indents

---

Cargo.toml

`tree-sitter` has released changes that are breaking within its library itself, but that do not bump the ABI_VERSION. This means that although the `tree-sitter` "major version" has changed, this is compatible across major versions.

Loosen tree-sitter dependency versions

---

grammar.js
test/corpus/classes.txt

I elected to specify this as a `property_modifier` given that it's a property of both actors and functions. I considered creating a whole `actor_declaration` node but that seemed a little much. Happy to move this around if needs be.

Recognize `distributed` as a modifier on actors and functions.

---

queries/highlights.scm

(the missing highlighting for `true` above is a tree-sitter bug, I believe)

Highlight precedencegroup components.

---

bindings/rust/lib.rs
queries/injections.scm

This will allow components of regexen to be highlighted on GitHub, in the manner of those in JS and Ruby.

Add injections for regex highlighting.

---

grammar.js
test/corpus/functions.txt
test/corpus/statements.txt

This adds new rules for parameter packs and expansions in both type and expression position. Since this includes the keyword "repeat", which was already a keyword for a do-while loop, we must modify the do-while loop rule so that it remains valid long enough to disqualify the parameter-pack interpretation.
With this change, it's starting to look like the "contextual keyword that is special cased as an identifier" pattern is going to become more standard. To facilitate that, this creates an explicit (hidden) rule for it.
Fixes #381

Add support for SE-0393

---

Cargo.toml

Reverts alex-pinkus/tree-sitter-swift#379
This leads to dependency resolution issues where two versions of `tree-sitter` end up in the binary -- see #386

Revert "Loosen tree-sitter dependency versions"

---

.github/workflows/publish.yml
scripts/write-generated-grammar.sh

Some tasks that only run on publish still need modernization -- since they didn't run on PR, the issues didn't come up until merge.

Update github actions for publish tasks

---

binding.gyp
package.json

The tree-sitter executable gets downloaded as a binary during the
build, which is notably asynchronous -- this is why
`scripts/wait-for-tree-sitter.js` exists. The code in `binding.gyp`
therefore needs to run that before generating the header files.

Wait for tree-sitter from node-gyp

---

queries/outline.scm
test/outline/outline.swift

`outline.scm` file added.
It handles declarations of 
- `protocol`, 
- `actor`, 
- `class`, 
- `struct`, 
- `enum`
- `extension`
- `func` (both global and methods)
- type properties
In sake of performance and simplicity it captures the whole line from whatever `keyword` till `*_body`.
Verbosity in functions and types symbols made by purpose, in sake of simplicity and performance (every time i tried to make capture more precise in function especially ended up 60 sec warmup of zed on those grammars.

Outline implemented

---

package.json

This is a little cleanup. I learned that NPM puts binaries from dev dependencies on the path automatically when running scripts. Therefore, the explicit call to npx is not necessary in the scripts in package.json. Apologies for the churn!

Code cleanup

---

tree-sitter.json

Hi @alex-pinkus, thanks for the amazing work!
I've noticed that newer versions of tree-sitter (I'm currently using 0.24.2) [require a `tree-sitter.json` file](https://tree-sitter.github.io/tree-sitter/creating-parsers#command-init) in the root directory, instead of specifying settings under the `tree-sitter` key in `package.json`. While running `tree-sitter generate` automatically migrates to the config file, using this grammar as a npm dependency fails because the `tree-sitter.json` file is expected to be present.
This PR adds the `tree-sitter.json` config file. I’ve kept the `tree-sitter` key in `package.json` for backwards compatibility with older versions.

Add `tree-sitter.json` for compatibility with newer versions of tree-sitter

---

go.mod

Update go.mod to use the correct GitHub link

---

grammar.js
test/corpus/literals.txt

Swift supports [hexadecimal floating-point literals](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/lexicalstructure/#Floating-Point-Literals). This PR adds support for them.
E.g.
```swift
0x1.921F_B544_42D1_8000p1 == 3.141592_653589_7932
```

Add support for hex real literals

---

README.md
package-lock.json
package.json
test-npm-package/package-lock.json
test-npm-package/package.json

> This is a draft PR until I or the maintainers can test it.
This PR updates `tree-sitter-cli` and `tree-sitter` to match the versions in `tree-sitter-obj`.

Update `tree-sitter` peer dependency and `tree-sitter-cli` dependency.

---

grammar.js
package-lock.json
queries/highlights.scm
test/corpus/classes.txt

Add support for parsing code like this:
```swift
struct Foo<T: ~Copyable>: ~Copyable {
let bar: T
}
```

Add support for suppressed copyable constraints

---

.prettierrc.json
grammar.js
src/scanner.c
test/corpus/literals.txt
test/corpus/macros.txt
test/corpus/statements.txt
test/highlight/AppDelegate.swift

Fixes #438
This is _conceptually_ a one liner, just adding a `macro_invocation` rule. However, it's made more complicated because of existing use of the `#` symbol (regex/string literals, and directives/diagnostics).
Previously, with the former usage occupying expression position and the latter usage in extras with custom token precedence, we could get away with using the external scanner for only some of them. However, this new usage has caused the worlds to collide.
The initial fix for that is easy -- unify all of the actual `#` symbols to [Ca new external-scanner token we emit when we see one `#` and not a string after it. However, that causes issues with directives because of their custom token precedence (which cannot be combined with external scanners). We thus need to parse the …

Add support for freestanding macros

---

grammar.js
test/corpus/functions.txt
test/corpus/literals.txt

Fixes #486
Adds a new helper, `sep1Opt`, that allows the separator to optionally
occur at the end.
It would have been nice to just change the behavior of `sep1` (since
we are allowed to be more permissive than the actual grammar) but
that introduces some parsing ambiguities in cases with other
separators, like enums.

Expand trailing comma support

---

scripts/write-generated-grammar.sh
setup.py

Most of the changes from #433 related to building from source, but
instead we're just going to publish from the generated-files branch.
However, the lines about `license` and `python_requires` seem useful
regardless. And if we're going to publish from that branch, we
should also sync this script to that branch.

Update setup.py to declare a license
