corpus/classes.txt
corpus/expressions.txt
corpus/functions.txt
grammar.ts
src/scanner.c

Fixing a few compile warnings in `scanner.c`, and making some tokens
visible for downstream packages.

Minor package cleanup

---

.github/workflows/publish.yml
.gitignore
package-lock.json
package.json
scripts/test-with-memcheck.sh
test-npm-package/index.js
test-npm-package/package-lock.json
test-npm-package/package.json

Also adds a small test-npm-package that uses the published code to parse
hello world. If it fails, nothing is published.
Fixes #87

Add a workflow for publishing to NPM

---

.github/workflows/publish.yml
Cargo.toml
README.md
bindings/rust/build.rs
bindings/rust/lib.rs

Also update the `README` to lead with instructions for using the crate
and the npm package. This is the future!

Update publish workflow to go to crates.io too

---

corpus/classes.txt
corpus/expressions.txt
corpus/functions.txt
corpus/statements.txt
grammar.js
queries/highlights.scm
script-data/known_failures.txt

- Fix @Sendable on lambda definitions
- Support async in variables and effects

Fix top-repo errors from version upgrades

---

grammar.js

This code was using simplified function syntax previously, but that got
lost in the journey to Typescript and back. This restores the original
syntax.

Use simplified function syntax for rules

---

.github/workflows/check.yml

On any new change, `PREFIX=/tmp make install` should succeed as long as
the parser has already been built.

Check C bindings in GitHub Actions

---

grammar.js

Remove duplicate grammar fragment for range operators

---

grammar.js

This is already included in the rule two lines above.

Remove duplicate equality_expression entry in binary_expression rule

---

corpus/literals.txt
src/scanner.c

Fix hang for incomplete raw strings

---

package.json

add config used by eg. `tree-sitter-cli`

Add project config

---

.gitignore
queries/tags.scm

add `tags.scm` usable for code navigation
https://tree-sitter.github.io/tree-sitter/code-navigation-systems

Add tags definitions

---

queries/highlights.scm

Based on the same updates in:
https://github.com/nvim-treesitter/nvim-treesitter/pull/3300

Update queries to add new keywords

---

README.md

Added instructions for using wasm based tree-sitter-swift.

Added instructions for tree-sitter-swift in Web Assembly

---

scripts/write-generated-grammar.sh

My attempt at fixing https://github.com/alex-pinkus/tree-sitter-swift/issues/239
I was a little confused about this, because the Package.swift file and swift bindings don't need this. Is this really the right solution?

Include Make stuff in with-generated-files

---

scripts/write-generated-grammar.sh

This may help with the latency issues described in #240﻿

Build ABI 14 as well as 13 when generating the grammar

---

grammar.js
test/corpus/expressions.txt

Fix precedence of prefix expressions vs nav expressions

---

grammar.js
test/corpus/expressions.txt

Reverts alex-pinkus/tree-sitter-swift#275

Revert "Fix precedence of prefix expressions vs nav expressions"

---

grammar.js
test/corpus/annotations.txt
test/corpus/classes.txt
test/corpus/emojis.txt
test/corpus/expressions.txt
test/corpus/functions.txt
test/corpus/literals.txt
test/corpus/statements.txt
test/corpus/types.txt

Exposes binding pattern kind and updates the tests.

Expose binding pattern kind

---

package-lock.json
package.json

When trying to run `npm install` locally, was seeing the issue [described here](https://github.com/nodejs/nan/issues/942).
Updating to `nan 2.18` fixed it! 
`macos 14.0, npm 10.2.0, node v.21.1.0`

Update nan 2.15 -> 2.18

---

scripts/write-generated-grammar.sh

Switch the default ABI on `with-generated-files`

---

scripts/write-generated-grammar.sh

Create tags pointing at with-generated-files commits

---

Cargo.toml
Makefile
README.md
package-lock.json
package.json
test-npm-package/package-lock.json

Release 0.4.1

---

.github/workflows/check.yml
.github/workflows/generate-static-grammar.yml
.github/workflows/parser-src.yml
.github/workflows/publish.yml
.github/workflows/test-older-tree-sitter.yml
.github/workflows/top-repos.yml
.github/workflows/update-repos.yml
README.md
grammar.js
package-json-old-tree-sitter.json
queries/highlights.scm
queries/tags.scm
test/corpus/classes.txt
test/corpus/statements.txt

Rebase and fixup of #286
Fixes #285

Create a separate identifier for constructors

---

grammar.js
queries/highlights.scm

All of the changes from #383, with my suggested addition to `_contextual_simple_identifier` and the appropriate conflicts resolved.

Finish PR #383

---

queries/locals.scm

Declare `lambda_expression` in scopes

---

queries/outline.scm
test/outline/outline.swift

Missed enum and protocol missed balue fixed.

Outline fixes

---

pyproject.toml

Use https://github.com/alex-pinkus/tree-sitter-swift and not https://github.com/tree-sitter/tree-sitter-swift

Use correct URL for project home
